spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.xml'

  datasource:
    url: jdbc:mariadb://localhost/employees
    username: employees
    password: employees

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    env:
      show-values: ALWAYS
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  appname: Employees
  contact: info@example.com

logging:
    level:
      employees: debug
    file:
      name: employee.log


message: Hello (from application.yaml)