spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mariadb://localhost/employees
    username: employees
    password: employees

logging:
    level:
      employees: debug
message: Hello (from application.yaml)