version: '3'

services:
  keycloak:
    container_name: keycloak
    image: codingpuss/keycloak-silicon:16.1.1
    restart: always
    env_file: ./keycloak.env
    depends_on:
      - keycloak_db

    ports:
      - "18080:8080"
    networks:
      - keycloak-net


  keycloak_db:
    container_name: keycloak_db
    image: mariadb:10.6.0
    restart: always
    volumes:
      - keycloak_db_vol:/var/lib/mysql
    env_file:
      - ./keycloak-db.env
    networks:
      - keycloak-net

volumes:
  keycloak_db_vol:

networks:
  keycloak-net: